services:

  # -------------------------
  # Reverse Proxy / TLS
  # -------------------------
  caddy:
    image: caddy:2.8
    container_name: liveauth-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./LiveAuthWeb/dist/liveauth-web:/srv
    depends_on:
      - liveauth-api
    networks:
      - liveauth

  # -------------------------
  # LiveAuth API (.NET)
  # -------------------------
  liveauth-api:
    image: liveauth-api:latest
    build:
      context: ./LiveAuthCore
      dockerfile: Dockerfile
    container_name: liveauth-api
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Data Source=/data/liveauth.db
      DB_PROVIDER: sqlite
      Admin__SkipPayment: "true"
      GitHub__ClientId: "Ov23li5BIPiYaNfLaBsn"
      GitHub__ClientSecret: "0ee4f29d2b7374442cffb739f455f8db0acc900e"
      LiveAuth__PowHmacSecret: "17b6b192e379f5689f87d99bf06510dc83e71de2d7429666bdb1c1437b6bd9e0"
    volumes:
      - sqlite_data:/data
    networks:
      - liveauth

networks:
  liveauth:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  sqlite_data:
